name: CI

on:
  push:
    branches:
      - master

jobs:
  test-and-build:
    runs-on: self-hosted

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '16'

      - name: Run unit tests
        run: |
          npm run test > test-report .txt || echo "Test failed" > test-report.txt

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: result.txt

      - name: Install Docker Engine
        uses: docker/setup-buildx-action@v2
        with:
          version: 'latest'

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Version with date-time
        run: |
          DATE=$(date +%Y%m%d)
          TIME=$(date +%H%M%S)
          VERSION="1.0.0-${DATE}.${TIME}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker build -t kikelomo22/new-image:${VERSION} .
      - name: send notification
        uses: dawidd6/action-send-mail@v4
        with: 
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          to: afeadetutu@gmail.com
          from: afeadetutu@gmail.com
          body: Build job of ${{github.repository}} completed successfully!